// LOCAL
const ADD_TASK = "ADD_TASK";
const REMOVE_TASK = "REMOVE_TASK";
const TOGGLE_TASK = "TOGGLE_TASK";
const RECEIVE_TASKS = "RECEIVE_TASKS";

// API
const SIGNUP_USER = "SIGNUP_USER";
const LOGIN_USER = "LOGIN_USER";
const SET_LOGGED_USER = "SET_LOGGED_USER";
const LOGOUT_USER = "LOGOUT_USER";
const ADD_TASK_API = "ADD_TASK_API";
const UPDATE_TASK_API = "UPDATE_TASK_API";
const DELETE_TASK_API = "DELETE_TASK_API";
const ADD_LIST_API = "ADD_LIST_API";
const UPDATE_LIST_API = "UPDATE_LIST_API";
const DELETE_LIST_API = "DELETE_LIST_API";

export {
    ADD_TASK,
    REMOVE_TASK,
    TOGGLE_TASK,
    RECEIVE_TASKS,
    SIGNUP_USER,
    LOGIN_USER,
    SET_LOGGED_USER,
    LOGOUT_USER,
    ADD_TASK_API,
    UPDATE_TASK_API,
    DELETE_TASK_API,
    ADD_LIST_API,
    UPDATE_LIST_API,
    DELETE_LIST_API
};