const ADD_TASK = "ADD_TASK";
const REMOVE_TASK = "REMOVE_TASK";
const TOGGLE_TASK = "TOGGLE_TASK";
const RECEIVE_TASKS = "RECEIVE_TASKS";
const SET_LOGGED_USER = "SET_LOGGED_USER";

export {
    ADD_TASK,
    REMOVE_TASK,
    TOGGLE_TASK,
    RECEIVE_TASKS,
    SET_LOGGED_USER
};